-- Snowflake Read‑Only Role (execute as ACCOUNTADMIN or SECURITYADMIN)
CREATE ROLE IF NOT EXISTS READ_ONLY_ROLE;

-- Replace YOUR_WAREHOUSE / YOUR_DATABASE / YOUR_SCHEMA as needed
GRANT USAGE ON WAREHOUSE YOUR_WAREHOUSE TO ROLE READ_ONLY_ROLE;
GRANT USAGE ON DATABASE YOUR_DATABASE TO ROLE READ_ONLY_ROLE;
GRANT USAGE ON SCHEMA YOUR_DATABASE.YOUR_SCHEMA TO ROLE READ_ONLY_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA YOUR_DATABASE.YOUR_SCHEMA TO ROLE READ_ONLY_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA YOUR_DATABASE.YOUR_SCHEMA TO ROLE READ_ONLY_ROLE;

-- Assign role to a user
GRANT ROLE READ_ONLY_ROLE TO USER YOUR_USER;
